### ISSUE TITLE
when highlighting multiple entities in the hierarchy, moving one w the arrow (translation) should move them all 

### ISSUE THREAD

**Issue by ethereumdegen** [rewin123/space_editor#204] opened 2024-02-20 17:05 UTC
when highlighting multiple entities in the hierarchy, moving one w the arrow (translation) should move them all

**Comment by rewin123** [comment] 2024-02-20 17:30
Hold Shift to activate cooperative move

**Comment by naomijub** [comment] 2024-02-21 00:11
Added to documentation: [f4987a9](https://github.com/rewin123/space_editor/commit/f4987a9610d53fedead41afa60378d888d8df54e)

**Comment by ethereumdegen** [comment] 2024-02-21 02:50
this does not solve it for me. it must be a bug .  i do see multiple gizmos but cant move them together even with SHIFT

**Comment by naomijub** [comment] 2024-02-21 03:09
What is your OS?

**Comment by rewin123** [comment] 2024-02-21 09:12
I found same bug on windows. Looks like dropped functionality

**Comment by Severencir** [comment] 2024-02-23 03:55
The issue seems to be caused by the conditional at line: 113 of crates/editor_ui/src/tools/gizmo.rs

the conditional never seems to be true, and seems to affect other customizable hotkeys. removing the first part of the conditional `ui.ui_contains_pointer()` fixes the issue, but i am too much of a novice to know if leaving that removed would cause undesirable behavior. i would fork it and submit a PR, but i honestly am almost completely new to collab and don't know how.

**Comment by naomijub** [comment] 2024-02-23 06:16
@Severencir If you are confident that this fixes the issue, feel free to submit a PR and we can test it on our end, but your observation seems correct from what I have tested (works on Windows and Mac)

**Comment by Severencir** [comment] 2024-02-23 07:14
i think i did that right. from the testing i did, the removal seems to have no negative effect on usage since keypresses aren't handled if the scene view doesn't have focus anyway

**Comment by naomijub** [comment] 2024-02-23 08:10
Thanks @Severencir. Now holding shift works @ethereumdegen just checked in windows and Mac

**Comment by rewin123** [comment] 2024-02-25 15:10
Oh, I've fixed a fixed issue in my PR xDD

**Closed** 2024-02-25 21:16 UTC
Labels: bug
